### ISSUE TITLE
Calendar usage limits exceeded

### ISSUE THREAD

**Issue by insanum** [gdenning/exchange-sync#15]
Great application by the way. Fits my needs perfectly!

So every time I tried to sync I would get the "Calendar usage limits exceeded" error message. Surprisingly, I inserted a one second delay between single event updates and that didn't fix it. Based on this help page (https://support.google.com/a/answer/2905486?hl=en), I figured the issue had to due with the list of attendees.

If you comment out the two "if blocks" that set the organizer and attendees in populateEventFromAppointmentDto() in the file GoogleCalendarSourceImpl.java the problem goes away.
I'd supply a pull request but commenting this out probably isn't desired. Syncing the attendees should be an option.

**Comment by gdenning** [comment]
Thanks for the feedback!  I've added a new setting to exchangesync.properties called "googleSyncOrganizerAndAttendees" that can now be set to false to prevent this issue from happening.  However, I'm guessing that you were getting that issue because it was your initial export and there were a lot of appointments to export. Going forward, you can probably re-enable that setting and it should work fine. I haven't seen that "Calendar usage limits exceeded" error for a long time.

**Comment by manjeshpv** [comment]
After analysing logs, I found

Below Limits for Create

Free Google Apps Account For a user: Initially: 100 Extenal Guests Domains Emails limit Accumulative: 1 External Guest for 40 Minutes

Ex: If you have a fresh token you can send any one *. 50 Events having 100 guest - 2 Guests per event *. 25 Events having 100 guest - 4 Guests per event

Limits per Day: 36 Guests Week: 252 Guests month: ~1080 Guests

Where Purchased GSuite Calendar API gives initial limit of 1000 Guest Request

https://github.com/manjeshpv/gsuite-google-calendar-api-limits
